### ISSUE TITLE
Making the text or drawings clickable

### ISSUE THREAD

**Issue by mikeyhalla** [JohnnyCrazy/DX9-Overlay-API-Wrapper#5]
Is there anyway so that I can make an event if someone clicks on text or drawings I put into the game overlays? For example a link that opens the default browser to the link?

**Comment by shadowlif** [comment]
see https://github.com/agrippa1994/DX9-Overlay-API/issues/31
Also see https://msdn.microsoft.com/en-us/library/9bt8ty58(v=vs.110).aspx and https://msdn.microsoft.com/en-us/library/69ye7hc8(v=vs.110).aspx
For the mouse position and the click detection you can use Global Mouse Hook (search it on Google).

**Comment by mikeyhalla** [comment]
Thanks a lot. Obviously I am new to the DirectX world and pretty much figured it would be as you answered.
