### ISSUE TITLE
Not working for DX10 Games

### ISSUE THREAD

**Issue by xCONFLiCTiONx** [JohnnyCrazy/DX9-Overlay-API-Wrapper#6]
Man, I'm sorry for making this an issue but you dll is the one working for me except I need one for dx10 games too. I search and find for dx9 and dx11 only. Why nothing for dx10? What am I missing here? Thank you for your time.

**Comment by ghost** [comment]
Related to https://github.com/agrippa1994/DX9-Overlay-API/issues/37
As soon as the API supports DX10/11, the wrapper support it also.
